### ISSUE TITLE
大佬！

### ISSUE THREAD

**Issue by senkiss** [ty01528/fortaSlaViewer#1]
感谢开发。能不能搞个分组还有IP地址的功能！有问题好知道是哪台机，分组就是知道是谁的机器。能不能搞批量添加功能就是一行一个地址直接可以复制进去自动编号或者文本格式直接可能导入

**Comment by ty01528** [comment]
支持多行导入的，一行一个地址，整体粘贴就可以；备注与分组的功能正在开发ing

**Comment by ty01528** [comment]
备注功能也已完成

**Comment by senkiss** [comment]
我用了你的新版本没有备注？能不能把分数加颜色！比如0.75以上就是绿色显示！0.75一下就是红色！这样机器多的时候一眼就能看出状态是不是正常

**Comment by senkiss** [comment]
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 2675 [running]:
ginProject/src/handler.GetRealTimeScore({0xc0004f1740?, 0xc00008a9b0?})
	C:/Users/ty/GolandProjects/fortaSlaViewer/src/handler/GetScore.go:26 +0x3df
ginProject/src/handler.GetScoreFromLeveldb.func1()
	C:/Users/ty/GolandProjects/fortaSlaViewer/src/handler/GetScoreFromLeveldb.go:18 +0x65
created by ginProject/src/handler.GetScoreFromLeveldb
	C:/Users/ty/GolandProjects/fortaSlaViewer/src/handler/GetScoreFromLeveldb.go:15 +0x1b1
会报这个错误自动退出！LIUNX的如果以127.0.0.1会访问不了！以0.0.0.0指定端口可以打开一次然后程序就退出报上面的错误
然后如果指定物理网卡IP地址和端口启动目前正常！

**Comment by ty01528** [comment]
这个好像是LevelDB的版本问题，我来编译一下试试

**Comment by senkiss** [comment]
还是老是自动崩溃！跟上面一样！是不是跟python版本有关?

**Comment by ty01528** [comment]
不是用python构建的，可以尝试将二进制文件添加到systemd守护程序

**Comment by senkiss** [comment]
加了谢谢！另外i就是分数加色的问题了！
